language:      node_js
git:
  depth:       3
node_js:
  - "node"
install:       npm install
script:
  - npm run-script build
cache:
  directories:
    - node_modules
notifications:
  email:       admin@bitcoinAnd.net
